# Generated by Django 2.0 on 2018-06-03 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0003_auto_20180603_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 3, 12, 53, 45, 759873, tzinfo=utc)),
        ),
    ]
