# Generated by Django 2.0 on 2018-05-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['last_updated_time']},
        ),
    ]
